import './globals.css'
import Header from './components/Header'
import { barlowCondensed } from './fonts';



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${barlowCondensed.className} max-w-screen min-h-screen text-white`}>
          {children}
        </body>
    </html>
  )
}
